version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: face_recog
      POSTGRES_USER: faceuser
      POSTGRES_PASSWORD: facepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      # Set DATABASE_URL to point to the Postgres container
      DATABASE_URL: postgres://faceuser:facepass@db:5432/face_recog
      PROVIDER: CPU
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:

# Usage:
# docker-compose up --build
# The backend will be available on http://localhost:8000
# The postgres data is persisted to the docker volume 'postgres_data'.